"""ai settings

Revision ID: 467f115236d2
Revises: 759ce1740351
Create Date: 2026-07-21 04:28:48.703490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '467f115236d2'
down_revision: Union[str, None] = '759ce1740351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=True),
    sa.Column('openrouter_key_encrypted', sa.Text(), nullable=True),
    sa.Column('default_model', sa.String(length=120), nullable=True),
    sa.Column('fast_model', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    # NOTE: autogenerate wanted to drop ix_documents_text_fts (it's a manual
    # expression index unknown to the models) — kept deliberately.


def downgrade() -> None:
    op.drop_table('ai_settings')
