"""databases: page kind, properties, views, values

Revision ID: 8407887ece57
Revises: cb1cff7e647a
Create Date: 2026-07-20 19:49:24.298755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8407887ece57'
down_revision: Union[str, None] = 'cb1cff7e647a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_properties_database_id'), 'db_properties', ['database_id'], unique=False)
    op.create_table('db_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_views_database_id'), 'db_views', ['database_id'], unique=False)
    op.create_table('db_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('row_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['db_properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'property_id')
    )
    op.create_index(op.f('ix_db_values_property_id'), 'db_values', ['property_id'], unique=False)
    op.create_index(op.f('ix_db_values_row_id'), 'db_values', ['row_id'], unique=False)
    op.add_column('pages', sa.Column('kind', sa.String(length=16), server_default='doc', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'kind')
    op.drop_index(op.f('ix_db_values_row_id'), table_name='db_values')
    op.drop_index(op.f('ix_db_values_property_id'), table_name='db_values')
    op.drop_table('db_values')
    op.drop_index(op.f('ix_db_views_database_id'), table_name='db_views')
    op.drop_table('db_views')
    op.drop_index(op.f('ix_db_properties_database_id'), table_name='db_properties')
    op.drop_table('db_properties')
    # ### end Alembic commands ###
