"""ydoc update log + collab seed marker

Revision ID: cb1cff7e647a
Revises: 423c470fd63d
Create Date: 2026-07-20 14:35:19.924973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb1cff7e647a'
down_revision: Union[str, None] = '423c470fd63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ydoc_updates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ydoc_updates_page_id'), 'ydoc_updates', ['page_id'], unique=False)
    op.add_column('documents', sa.Column('collab_seeded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'collab_seeded_at')
    op.drop_index(op.f('ix_ydoc_updates_page_id'), table_name='ydoc_updates')
    op.drop_table('ydoc_updates')
    # ### end Alembic commands ###
